export default {
  GET_CANDIDATES_REQUEST: '@candidates/GET_CANDIDATES_REQUEST',
  GET_CANDIDATES_SUCCESS: '@candidates/GET_CANDIDATES_SUCCESS',
  GET_CANDIDATES_FAILURE: '@candidates/GET_CANDIDATES_FAILURE',

  ADD_CANDIDATE: '@candidates/ADD_CANDIDATE',
};
